# workspace:
#   base: /drone/src
#   path: ./
pipeline:
  
  # build-master:
  #   image: 'node:10.6.0'
  #   commands:
  #     - 'npm install -g cnpm --registry=https://registry.npm.taobao.org'
  #     - 'cnpm install'
  #     - 'cnpm run build'
  #   when:
  #     branch: master
  public-online:      
    image: plugins/docker 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    commands:
      - 'echo hello'
    when: 
      branch: master  
